### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.DynamicFeeTx).R

### ISSUE THREAD

**Issue by q9f** [q9f/eth.rb#54]
https://github.com/q9f/eth.rb/runs/4895235740?check_suite_focus=true

```
Failures:

  1) Eth::Client.transfer .transfer_and_wait funds a random account using legacy transactions
     Failure/Error: raise IOError, output["error"]["message"] unless output["error"].nil?

     IOError:
       rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.DynamicFeeTx).R
     # ./lib/eth/client.rb:207:in `send_command'
     # ./lib/eth/client.rb:191:in `block (2 levels) in <class:Client>'
     # ./lib/eth/client.rb:141:in `transfer'
     # ./lib/eth/client.rb:101:in `transfer_and_wait'
     # ./spec/eth/client_spec.rb:65:in `block (3 levels) in <top (required)>'
```
